var newkana = [
	["ゎ", "&ぅぁ;", "ゎ", "HIRAGANA LETTER SMALL WA"],
	["ゐ", "&うぃ;", "ゐ", "HIRAGANA LETTER WI"],
	["ゑ", "&うぇ;", "ゑ", "HIRAGANA LETTER WE"],

	["ヮ", "&ゥァ;", "ヮ", "KATAKANA LETTER SMALL WA"],
	["ヰ", "&ウィ;", "ヰ", "KATAKANA LETTER WI"],
	["ヱ", "&ウェ;", "ヱ", "KATAKANA LETTER WE"],

	["ヷ", "ワﾞ", "ヷ", "KATAKANA LETTER VA"],
	["ヸ", "&ヴィ;", "ヸ", "KATAKANA LETTER VI"],
	["ヹ", "&ヴェ;", "ヹ", "KATAKANA LETTER VE"],
	["ヺ", "ヲﾞ", "ヺ", "KATAKANA LETTER VO"],

	["ㇰ", "&ノハク;", "ㇰ", "KATAKANA LETTER SMALL KU"],
	["ㇱ", "&ノハシ;", "ㇱ", "KATAKANA LETTER SMALL SHI"],
	["ㇲ", "&ノハス;", "ㇲ", "KATAKANA LETTER SMALL SU"],
	["ㇳ", "&ノハト;", "ㇳ", "KATAKANA LETTER SMALL TO"],
	["ㇴ", "&ノハヌ;", "ㇴ", "KATAKANA LETTER SMALL NU"],
	["ㇵ", "&ノハハ;", "ㇵ", "KATAKANA LETTER SMALL HA"],
	["ㇶ", "&ノハヒ;", "ㇶ", "KATAKANA LETTER SMALL HI"],
	["ㇷ", "&ノハフ;", "ㇷ", "KATAKANA LETTER SMALL HU"],
	["ㇸ", "&ノハヘ;", "ㇸ", "KATAKANA LETTER SMALL HE"],
	["ㇹ", "&ノハホ;", "ㇹ", "KATAKANA LETTER SMALL HO"],
	["ㇺ", "&ノハム;", "ㇺ", "KATAKANA LETTER SMALL MU"],
	["ㇻ", "&ノハラ;", "ㇻ", "KATAKANA LETTER SMALL RA"],
	["ㇼ", "&ノハリ;", "ㇼ", "KATAKANA LETTER SMALL RI"],
	["ㇽ", "&ノハル;", "ㇽ", "KATAKANA LETTER SMALL RU"],
	["ㇾ", "&ノハレ;", "ㇾ", "KATAKANA LETTER SMALL RE"],
	["ㇿ", "&ノハロ;", "ㇿ", "KATAKANA LETTER SMALL RO"],

	["", "ぁ^", "ぁˆ", "HIRAGANA LETTER SMALL SCHWA"],
	["", "あ^", "あˆ", "HIRAGANA LETTER SCHWA"],
	["", "ぃ^", "ぃˆ", "HIRAGANA LETTER SMALL Y"],
	["", "い^", "いˆ", "HIRAGANA LETTER Y"],
	["", "ぅ^", "ぅˆ", "HIRAGANA LETTER SMALL EU"],
	["", "う^", "うˆ", "HIRAGANA LETTER EU"],
	["", "ぇ^", "ぇˆ", "HIRAGANA LETTER SMALL AE"],
	["", "え^", "えˆ", "HIRAGANA LETTER AE"],
	["", "ぉ^", "ぉˆ", "HIRAGANA LETTER SMALL EO"],
	["", "お^", "おˆ", "HIRAGANA LETTER EO"],

	["", "ァ^", "ァˆ", "KATAKANA LETTER SMALL SCHWA"],
	["", "ア^", "アˆ", "KATAKANA LETTER SCHWA"],
	["", "ィ^", "ィˆ", "KATAKANA LETTER SMALL Y"],
	["", "イ^", "イˆ", "KATAKANA LETTER Y"],
	["", "ゥ^", "ゥˆ", "KATAKANA LETTER SMALL EU"],
	["", "ウ^", "ウˆ", "KATAKANA LETTER EU"],
	["", "ェ^", "ェˆ", "KATAKANA LETTER SMALL AE"],
	["", "エ^", "エˆ", "KATAKANA LETTER AE"],
	["", "ォ^", "ォˆ", "KATAKANA LETTER SMALL EO"],
	["", "オ^", "オˆ", "KATAKANA LETTER EO"],

	["", "&_シ;", "ｹシｾ", "KATAKANA LETTER KESEN SI"],
	["", "&_ジ;", "ｹジｾ", "KATAKANA LETTER KESEN ZI"],
	["", "&_ツ;", "ｹツｾ", "KATAKANA LETTER KESEN TI"],
	["", "&_ヅ;", "ｹヅｾ", "KATAKANA LETTER KESEN DI"],

	["", "&_すﾟ;", "ｹす゚ｾ", "HIRAGANA LETTER PINYIN SHI"],
	["", "&_ずﾟ;", "ｹずﾟｾ", "HIRAGANA LETTER PINYIN RI"],
	["", "&_ちﾟ;", "ｹち゚ｾ", "HIRAGANA LETTER KESEN TI WITH SEMI-VOICED SOUND MARK"],
	["", "&_ぢﾟ;", "ｹぢﾟｾ", "HIRAGANA LETTER PINYIN ZHI"],
	["", "&_ち.;", "ｹち.ｾ", "HIRAGANA LETTER PINYIN CI"],
	["", "&_ちﾟ.;", "ｹち゚.ｾ", "HIRAGANA LETTER PINYIN CHI"],
	["", "&_シﾟ;", "ｹシ゚ｾ", "KATAKANA LETTER PINYIN SHI"],
	["", "&_ジﾟ;", "ｹジﾟｾ", "KATAKANA LETTER PINYIN RI"],
	["", "&_ツﾟ;", "ｹツ゚ｾ", "KATAKANA LETTER KESEN TI WITH SEMI-VOICED SOUND MARK"],
	["", "&_ヅﾟ;", "ｹヅﾟｾ", "KATAKANA LETTER PINYIN ZHI"],
	["", "&_ツ.;", "ｹツ.ｾ", "KATAKANA LETTER PINYIN CI"],
	["", "&_ツﾟ.;", "ｹツ゚.ｾ", "KATAKANA LETTER PINYIN CHI"],

	["", "&すぃ;", "すｨ", "HIRAGANA LETTER SI"],
	["", "&ずぃ;", "ずｨ", "HIRAGANA LETTER ZI"],
	["", "&すﾟぃ;", "す゚ｨ", "HIRAGANA LETTER THI"],
	["", "ざﾟ", "ざﾟ", "HIRAGANA LETTER DHA"],
	["", "&ずﾟぃ;", "ずﾟｨ", "HIRAGANA LETTER DHI"],
	["", "ずﾟ", "ずﾟ", "HIRAGANA LETTER DHU"],
	["", "ぜﾟ", "ぜﾟ", "HIRAGANA LETTER DHE"],
	["", "ぞﾟ", "ぞﾟ", "HIRAGANA LETTER DHO"],
	["", "&ほぅ;", "ほｩ", "HIRAGANA LETTER HU-2"],
	["", "りﾟ", "り゚", "HIRAGANA LETTER LI"],
	["", "るﾟ", "る゚", "HIRAGANA LETTER LU"],
	["", "わﾞ", "わ゙", "HIRAGANA LETTER VA"],
	["", "&うﾞぃ;", "ゐ゙", "HIRAGANA LETTER VI"],
	["", "&うﾞ;", "ゔｩ", "HIRAGANA LETTER VU"],
	["", "&うﾞぇ;", "ゑ゙", "HIRAGANA LETTER VE"],
	["", "をﾞ", "を゙", "HIRAGANA LETTER VO"],
	["", "わﾟ", "わ゚", "HIRAGANA LETTER FA"],
	["", "&うﾟぃ;", "ゐ゚", "HIRAGANA LETTER FI"],
	["", "&うﾟ;", "う゚ｩ", "HIRAGANA LETTER FU"],
	["", "&うﾟぇ;", "ゑ゚", "HIRAGANA LETTER FE"],
	["", "をﾟ", "を゚", "HIRAGANA LETTER FO"],
	["", "&しゃ;", "しｬ", "HIRAGANA LETTER SHA"],
	["", "&しゅ;", "しｭ", "HIRAGANA LETTER SHU"],
	["", "&しぇ;", "しｪ", "HIRAGANA LETTER SHE"],
	["", "&しょ;", "しｮ", "HIRAGANA LETTER SHO"],
	["", "&じゃ;", "じｬ", "HIRAGANA LETTER ZHA"],
	["", "&じゅ;", "じｭ", "HIRAGANA LETTER ZHU"],
	["", "&じぇ;", "じｪ", "HIRAGANA LETTER ZHE"],
	["", "&じょ;", "じｮ", "HIRAGANA LETTER ZHO"],
	["", "&ちゃ;", "ちｬ", "HIRAGANA LETTER CHA"],
	["", "&ちゅ;", "ちｭ", "HIRAGANA LETTER CHU"],
	["", "&ちぇ;", "ちｪ", "HIRAGANA LETTER CHE"],
	["", "&ちょ;", "ちｮ", "HIRAGANA LETTER CHO"],
	["", "&ぢゃ;", "ぢｬ", "HIRAGANA LETTER JA"],
	["", "&ぢゅ;", "ぢｭ", "HIRAGANA LETTER JU"],
	["", "&ぢぇ;", "ぢｪ", "HIRAGANA LETTER JE"],
	["", "&ぢょ;", "ぢｮ", "HIRAGANA LETTER JO"],
	["", "&つぁ;", "つｧ", "HIRAGANA LETTER TSA"],
	["", "&つぇ;", "つｪ", "HIRAGANA LETTER TSE"],
	["", "&つぉ;", "つｫ", "HIRAGANA LETTER TSO"],
	["", "&づぁ;", "づｧ", "HIRAGANA LETTER DZA"],
	["", "&づぇ;", "づｪ", "HIRAGANA LETTER DZE"],
	["", "&づぉ;", "づｫ", "HIRAGANA LETTER DZO"],
	["", "&hん;", "hﾝ", "HIRAGANA LETTER HN"],
	["", "&bん;", "bﾝ", "HIRAGANA LETTER BN"],

	["", "&スィ;", "スｨ", "KATAKANA LETTER SI"],
	["", "&ズィ;", "ズｨ", "KATAKANA LETTER ZI"],
	["", "&スﾟィ;", "ス゚ｨ", "KATAKANA LETTER THI"],
	["", "ザﾟ", "ザﾟ", "KATAKANA LETTER DHA"],
	["", "&ズﾟィ;", "ズﾟｨ", "KATAKANA LETTER DHI"],
	["", "ズﾟ", "ズﾟ", "KATAKANA LETTER DHU"],
	["", "ゼﾟ", "ゼﾟ", "KATAKANA LETTER DHE"],
	["", "ゾﾟ", "ゾﾟ", "KATAKANA LETTER DHO"],
	["", "&ティ;", "テｨ", "KATAKANA LETTER TI"],
	["", "&ディ;", "デｨ", "KATAKANA LETTER DI"],
	["", "&ドゥ;", "ドｩ", "KATAKANA LETTER DU"],
	["", "&ホゥ;", "ホｩ", "KATAKANA LETTER HU-2"],
	["", "ワﾟ", "ワ゚", "KATAKANA LETTER FA"],
	["", "&ウﾟィ;", "ヰ゚", "KATAKANA LETTER FI"],
	["", "&ウﾟ;", "ウ゚ｩ", "KATAKANA LETTER FU"],
	["", "&ウﾟェ;", "ヱ゚", "KATAKANA LETTER FE"],
	["", "ヲﾟ", "ヲ゚", "KATAKANA LETTER FO"],
	["", "&ジャ;", "ジｬ", "KATAKANA LETTER ZHA"],
	["", "&ジュ;", "ジｭ", "KATAKANA LETTER ZHU"],
	["", "&ジェ;", "ジｪ", "KATAKANA LETTER ZHE"],
	["", "&ジョ;", "ジｮ", "KATAKANA LETTER ZHO"],
	["", "&ヂャ;", "ヂｬ", "KATAKANA LETTER JA"],
	["", "&ヂュ;", "ヂｭ", "KATAKANA LETTER JU"],
	["", "&ヂェ;", "ヂｪ", "KATAKANA LETTER JE"],
	["", "&ヂョ;", "ヂｮ", "KATAKANA LETTER JO"],
	["", "&ツァ;", "ツｧ", "KATAKANA LETTER TSA"],
	["", "&ツィ;", "ツｨ", "KATAKANA LETTER TSI"],
	["", "&ツェ;", "ツｪ", "KATAKANA LETTER TSE"],
	["", "&ツォ;", "ツｫ", "KATAKANA LETTER TSO"],
	["", "&ヅァ;", "ヅｧ", "KATAKANA LETTER DZA"],
	["", "&ヅィ;", "ヅｨ", "KATAKANA LETTER DZI"],
	["", "&ヅェ;", "ヅｪ", "KATAKANA LETTER DZE"],
	["", "&ヅォ;", "ヅｫ", "KATAKANA LETTER DZO"],
	["", "&fん;", "fﾝ", "KATAKANA LETTER HN"],
	["", "&vん;", "vﾝ", "KATAKANA LETTER BN"],

	["", "&ぃ.;", "&ぃ.;", "HIRAGANA LETTER SMALL I WITH DOT BELOW"],
	["", "&ぅ.;", "&ぅ.;", "HIRAGANA LETTER SMALL U WITH DOT BELOW"],
	["", "&ィ.;", "&ィ.;", "KATAKANA LETTER SMALL I WITH DOT BELOW"],
	["", "&ゥ.;", "&ゥ.;", "KATAKANA LETTER SMALL U WITH DOT BELOW"],

	["", "かﾟ", "か゚", "HIRAGANA LETTER NGA"],
	["", "きﾟ", "き゚", "HIRAGANA LETTER NGI"],
	["", "くﾟ", "く゚", "HIRAGANA LETTER NGU"],
	["", "けﾟ", "け゚", "HIRAGANA LETTER NGE"],
	["", "こﾟ", "こ゚", "HIRAGANA LETTER NGO"],
	["", "カﾟ", "カ゚", "KATAKANA LETTER NGA"],
	["", "キﾟ", "キ゚", "KATAKANA LETTER NGI"],
	["", "クﾟ", "ク゚", "KATAKANA LETTER NGU"],
	["", "ケﾟ", "ケ゚", "KATAKANA LETTER NGE"],
	["", "コﾟ", "コ゚", "KATAKANA LETTER NGO"],
	["", "セﾟ", "セ゚", "KATAKANA LETTER THE"],
	["", "ツﾟ", "ツ゚", "KATAKANA LETTER TSU WITH VOICED SOUND MARK"],
	["", "トﾟ", "ト゚", "KATAKANA LETTER TO WITH VOICED SOUND MARK"],
	["", "&ノハプ;", "ㇷ゚", "KATAKANA LETTER SMALL PU"],

	["", "さﾟ", "さ゚", "HIRAGANA LETTER THA"],
	["", "しﾟ", "し゚", "HIRAGANA LETTER SHI WITH VOICED SOUND MARK"],
	["", "すﾟ", "す゚", "HIRAGANA LETTER THU"],
	["", "せﾟ", "せ゚", "HIRAGANA LETTER THE"],
	["", "そﾟ", "そ゚", "HIRAGANA LETTER THO"],
	["", "サﾟ", "サ゚", "KATAKANA LETTER THA"],
	["", "シﾟ", "シ゚", "KATAKANA LETTER SHI WITH VOICED SOUND MARK"],
	["", "スﾟ", "ス゚", "KATAKANA LETTER THU"],
	["", "ソﾟ", "ソ゚", "KATAKANA LETTER THO"],
	["", "ラﾟ", "ラ゚", "KATAKANA LETTER LA"],
	["", "リﾟ", "リ゚", "KATAKANA LETTER LI"],
	["", "ルﾟ", "ル゚", "KATAKANA LETTER LU"],
	["", "レﾟ", "レ゚", "KATAKANA LETTER LE"],
	["", "ロﾟ", "ロ゚", "KATAKANA LETTER LO"],
	
	["", "&ヴ;", "ヴｩ", "KATAKANA LETTER VU"],

	["", "&とぅ;", "とｩ", "HIRAGANA LETTER TU"],
	["", "&どぅ;", "どｩ", "HIRAGANA LETTER DU"],
	["", "&てぃ;", "てｨ", "HIRAGANA LETTER TI"],
	["", "&でぃ;", "でｨ", "HIRAGANA LETTER DI"],
	["", "&つぃ;", "つｨ", "HIRAGANA LETTER TSI"],
	["", "&づぃ;", "づｨ", "HIRAGANA LETTER DZI"],

	["", "&チャ;", "チｬ", "KATAKANA LETTER CHA"],
	["", "&チュ;", "チｭ", "KATAKANA LETTER CHU"],
	["", "&チェ;", "チｪ", "KATAKANA LETTER CHE"],
	["", "&チョ;", "チｮ", "KATAKANA LETTER CHO"],
	["", "&シャ;", "シｬ", "KATAKANA LETTER SHA"],
	["", "&シュ;", "シｭ", "KATAKANA LETTER SHU"],
	["", "&シェ;", "シｪ", "KATAKANA LETTER SHE"],
	["", "&ショ;", "シｮ", "KATAKANA LETTER SHO"],
	["", "&トゥ;", "トｩ", "KATAKANA LETTER TU"],

	["", "&_す;", "ｹすｾ", "HIRAGANA LETTER KESEN SI"],
	["", "&_ず;", "ｹずｾ", "HIRAGANA LETTER KESEN ZI"],
	["", "&_ち;", "ｹちｾ", "HIRAGANA LETTER KESEN TI"],
	["", "&_ぢ;", "ｹぢｾ", "HIRAGANA LETTER KESEN DI"],

	["", "らﾟ", "ら゚", "HIRAGANA LETTER LA"],
	["", "れﾟ", "れ゚", "HIRAGANA LETTER LE"],
	["", "ろﾟ", "ろ゚", "HIRAGANA LETTER LO"],

	["𛀁", "&いぇ;", "いｪ", "HIRAGANA LETTER YE"],
	["𛀆", "&いぃ;", "いｨ", "HIRAGANA LETTER YI"],
	["𛄟", "&うぅ;", "うｩ", "HIRAGANA LETTER WU"],
	["𛄠", "&イィ;", "イｨ", "KATAKANA LETTER YI"],
	["𛄡", "&イェ;", "イｪ", "KATAKANA LETTER YE"],
	["𛄢", "&ウゥ;", "ウｩ", "KATAKANA LETTER WU"],

	["𛅄", "&ノハへ;", "ノﾊへ", "HIRAGANA LETTER SMALL HE"],
	["𛅐", "&ぅぃ;", "ぅｨ", "HIRAGANA LETTER SMALL WI"],
	["𛅑", "&ぅぇ;", "ぅｪ", "HIRAGANA LETTER SMALL WE"],
	["𛅒", "&ぅぉ;", "ぅｫ", "HIRAGANA LETTER SMALL WO"],
	["𛅓", "&ノハん;", "ノﾊん", "HIRAGANA LETTER SMALL N"],
	["𛅤", "&ゥィ;", "ゥｨ", "KATAKANA LETTER SMALL WI"],
	["𛅥", "&ゥェ;", "ゥｪ", "KATAKANA LETTER SMALL WE"],
	["𛅦", "&ゥォ;", "ゥｫ", "KATAKANA LETTER SMALL WO"],
	["𛅧", "&ノハン;", "ノﾊン", "KATAKANA LETTER SMALL N"],

	["󷰹", "&ぃぇ;", "ぃｪ", "HIRAGANA LETTER SMALL YE"],
	["󷰼", "&ィェ;", "ィｪ", "KATAKANA LETTER SMALL YE"],

	["ゔ", "うﾞ", "ゔ", "HIRAGANA LETTER VU"],

	["", "ﾞﾟ", "゙ﾟ", "COMBINING KATAKANA-HIRAGANA VOICED SEMI-VOICED SOUND MARK"],
	["", "ﾞﾟ", "゛ﾟ", "KATAKANA-HIRAGANA VOICED SEMI-VOICED SOUND MARK"],
	["", "ﾞﾟ", "ﾞﾟ", "HALFWIDTH KATAKANA-HIRAGANA VOICED SEMI-VOICED SOUND MARK"]
];