var newkana = [
	["ゎ", "&ぅぁ;", "ゎ", "Hiragana Letter Small Wa"],
	["ゐ", "&うぃ;", "ゐ", "Hiragana Letter Wi"],
	["ゑ", "&うぇ;", "ゑ", "Hiragana Letter We"],

	["ヮ", "&ゥァ;", "ヮ", "Katakana Letter Small Wa"],
	["ヰ", "&ウィ;", "ヰ", "Katakana Letter Wi"],
	["ヱ", "&ウェ;", "ヱ", "Katakana Letter We"],

	["ヷ", "ワﾞ", "ヷ", "Katakana Letter Va"],
	["ヸ", "&ヴィ;", "ヸ", "Katakana Letter Vi"],
	["ヹ", "&ヴェ;", "ヹ", "Katakana Letter Ve"],
	["ヺ", "ヲﾞ", "ヺ", "Katakana Letter Vo"],

	["ㇰ", "&ノハク;", "ㇰ", "Katakana Letter Small Ku"],
	["ㇱ", "&ノハシ;", "ㇱ", "Katakana Letter Small Shi"],
	["ㇲ", "&ノハス;", "ㇲ", "Katakana Letter Small Su"],
	["ㇳ", "&ノハト;", "ㇳ", "Katakana Letter Small To"],
	["ㇴ", "&ノハヌ;", "ㇴ", "Katakana Letter Small Nu"],
	["ㇵ", "&ノハハ;", "ㇵ", "Katakana Letter Small Ha"],
	["ㇶ", "&ノハヒ;", "ㇶ", "Katakana Letter Small Hi"],
	["ㇷ", "&ノハフ;", "ㇷ", "Katakana Letter Small Hu"],
	["ㇸ", "&ノハヘ;", "ㇸ", "Katakana Letter Small He"],
	["ㇹ", "&ノハホ;", "ㇹ", "Katakana Letter Small Ho"],
	["ㇺ", "&ノハム;", "ㇺ", "Katakana Letter Small Mu"],
	["ㇻ", "&ノハラ;", "ㇻ", "Katakana Letter Small Ra"],
	["ㇼ", "&ノハリ;", "ㇼ", "Katakana Letter Small Ri"],
	["ㇽ", "&ノハル;", "ㇽ", "Katakana Letter Small Ru"],
	["ㇾ", "&ノハレ;", "ㇾ", "Katakana Letter Small Re"],
	["ㇿ", "&ノハロ;", "ㇿ", "Katakana Letter Small Ro"],

	["", "ぁ^", "ぁˆ", "Hiragana Letter Small Schwa"],
	["", "あ^", "あˆ", "Hiragana Letter Schwa"],
	["", "ぃ^", "ぃˆ", "Hiragana Letter Small Y"],
	["", "い^", "いˆ", "Hiragana Letter Y"],
	["", "ぅ^", "ぅˆ", "Hiragana Letter Small Eu"],
	["", "う^", "うˆ", "Hiragana Letter Eu"],
	["", "ぇ^", "ぇˆ", "Hiragana Letter Small Ae"],
	["", "え^", "えˆ", "Hiragana Letter Ae"],
	["", "ぉ^", "ぉˆ", "Hiragana Letter Small Eo"],
	["", "お^", "おˆ", "Hiragana Letter Eo"],

	["", "ァ^", "ァˆ", "Katakana Letter Small Schwa"],
	["", "ア^", "アˆ", "Katakana Letter Schwa"],
	["", "ィ^", "ィˆ", "Katakana Letter Small Y"],
	["", "イ^", "イˆ", "Katakana Letter Y"],
	["", "ゥ^", "ゥˆ", "Katakana Letter Small Eu"],
	["", "ウ^", "ウˆ", "Katakana Letter Eu"],
	["", "ェ^", "ェˆ", "Katakana Letter Small Ae"],
	["", "エ^", "エˆ", "Katakana Letter Ae"],
	["", "ォ^", "ォˆ", "Katakana Letter Small Eo"],
	["", "オ^", "オˆ", "Katakana Letter Eo"],

	["", "&_シ;", "ｹシｾ", "Katakana Letter Kesen Si"],
	["", "&_ジ;", "ｹジｾ", "Katakana Letter Kesen Zi"],
	["", "&_ツ;", "ｹツｾ", "Katakana Letter Kesen Ti"],
	["", "&_ヅ;", "ｹヅｾ", "Katakana Letter Kesen Di"],

	["", "&_すﾟ;", "ｹす゚ｾ", "Hiragana Letter Pinyin Shi"],
	["", "&_ずﾟ;", "ｹずﾟｾ", "Hiragana Letter Pinyin Ri"],
	["", "&_ちﾟ;", "ｹち゚ｾ", "Hiragana Letter Kesen Ti With Semi-Voiced Sound Mark"],
	["", "&_ぢﾟ;", "ｹぢﾟｾ", "Hiragana Letter Pinyin Zhi"],
	["", "&_ち.;", "ｹち.ｾ", "Hiragana Letter Pinyin Ci"],
	["", "&_ちﾟ.;", "ｹち゚.ｾ", "Hiragana Letter Pinyin Chi"],
	["", "&_シﾟ;", "ｹシ゚ｾ", "Katakana Letter Pinyin Shi"],
	["", "&_ジﾟ;", "ｹジﾟｾ", "Katakana Letter Pinyin Ri"],
	["", "&_ツﾟ;", "ｹツ゚ｾ", "Katakana Letter Kesen Ti With Semi-Voiced Sound Mark"],
	["", "&_ヅﾟ;", "ｹヅﾟｾ", "Katakana Letter Pinyin Zhi"],
	["", "&_ツ.;", "ｹツ.ｾ", "Katakana Letter Pinyin Ci"],
	["", "&_ツﾟ.;", "ｹツ゚.ｾ", "Katakana Letter Pinyin Chi"],

	["", "&すぃ;", "すｨ", "Hiragana Letter Si"],
	["", "&ずぃ;", "ずｨ", "Hiragana Letter Zi"],
	["", "&すﾟぃ;", "す゚ｨ", "Hiragana Letter Thi"],
	["", "ざﾟ", "ざﾟ", "Hiragana Letter Dha"],
	["", "&ずﾟぃ;", "ずﾟｨ", "Hiragana Letter Dhi"],
	["", "ずﾟ", "ずﾟ", "Hiragana Letter Dhu"],
	["", "ぜﾟ", "ぜﾟ", "Hiragana Letter Dhe"],
	["", "ぞﾟ", "ぞﾟ", "Hiragana Letter Dho"],
	["", "&ほぅ;", "ほｩ", "Hiragana Letter Hu-2"],
	["", "りﾟ", "り゚", "Hiragana Letter Li"],
	["", "るﾟ", "る゚", "Hiragana Letter Lu"],
	["", "わﾞ", "わ゙", "Hiragana Letter Va"],
	["", "&うﾞぃ;", "ゐ゙", "Hiragana Letter Vi"],
	["", "&うﾞ;", "ゔｩ", "Hiragana Letter Vu"],
	["", "&うﾞぇ;", "ゑ゙", "Hiragana Letter Ve"],
	["", "をﾞ", "を゙", "Hiragana Letter Vo"],
	["", "わﾟ", "わ゚", "Hiragana Letter Fa"],
	["", "&うﾟぃ;", "ゐ゚", "Hiragana Letter Fi"],
	["", "&うﾟ;", "う゚ｩ", "Hiragana Letter Fu"],
	["", "&うﾟぇ;", "ゑ゚", "Hiragana Letter Fe"],
	["", "をﾟ", "を゚", "Hiragana Letter Fo"],
	["", "&しゃ;", "しｬ", "Hiragana Letter Sha"],
	["", "&しゅ;", "しｭ", "Hiragana Letter Shu"],
	["", "&しぇ;", "しｪ", "Hiragana Letter She"],
	["", "&しょ;", "しｮ", "Hiragana Letter Sho"],
	["", "&じゃ;", "じｬ", "Hiragana Letter Zha"],
	["", "&じゅ;", "じｭ", "Hiragana Letter Zhu"],
	["", "&じぇ;", "じｪ", "Hiragana Letter Zhe"],
	["", "&じょ;", "じｮ", "Hiragana Letter Zho"],
	["", "&ちゃ;", "ちｬ", "Hiragana Letter Cha"],
	["", "&ちゅ;", "ちｭ", "Hiragana Letter Chu"],
	["", "&ちぇ;", "ちｪ", "Hiragana Letter Che"],
	["", "&ちょ;", "ちｮ", "Hiragana Letter Cho"],
	["", "&ぢゃ;", "ぢｬ", "Hiragana Letter Ja"],
	["", "&ぢゅ;", "ぢｭ", "Hiragana Letter Ju"],
	["", "&ぢぇ;", "ぢｪ", "Hiragana Letter Je"],
	["", "&ぢょ;", "ぢｮ", "Hiragana Letter Jo"],
	["", "&つぁ;", "つｧ", "Hiragana Letter Tsa"],
	["", "&つぇ;", "つｪ", "Hiragana Letter Tse"],
	["", "&つぉ;", "つｫ", "Hiragana Letter Tso"],
	["", "&づぁ;", "づｧ", "Hiragana Letter Dza"],
	["", "&づぇ;", "づｪ", "Hiragana Letter Dze"],
	["", "&づぉ;", "づｫ", "Hiragana Letter Dzo"],
	["", "&ふん;", "ふﾝ", "Hiragana Letter Hn"],
	["", "&ぶん;", "ぶﾝ", "Hiragana Letter Bn"],
	["", "&ちっ;", "ちｯ", "Hiragana Letter Tsk"],

	["", "&スィ;", "スｨ", "Katakana Letter Si"],
	["", "&ズィ;", "ズｨ", "Katakana Letter Zi"],
	["", "&スﾟィ;", "ス゚ｨ", "Katakana Letter Thi"],
	["", "ザﾟ", "ザﾟ", "Katakana Letter Dha"],
	["", "&ズﾟィ;", "ズﾟｨ", "Katakana Letter Dhi"],
	["", "ズﾟ", "ズﾟ", "Katakana Letter Dhu"],
	["", "ゼﾟ", "ゼﾟ", "Katakana Letter Dhe"],
	["", "ゾﾟ", "ゾﾟ", "Katakana Letter Dho"],
	["", "&ティ;", "テｨ", "Katakana Letter Ti"],
	["", "&ディ;", "デｨ", "Katakana Letter Di"],
	["", "&ドゥ;", "ドｩ", "Katakana Letter Du"],
	["", "&ホゥ;", "ホｩ", "Katakana Letter Hu-2"],
	["", "ワﾟ", "ワ゚", "Katakana Letter Fa"],
	["", "&ウﾟィ;", "ヰ゚", "Katakana Letter Fi"],
	["", "&ウﾟ;", "ウ゚ｩ", "Katakana Letter Fu"],
	["", "&ウﾟェ;", "ヱ゚", "Katakana Letter Fe"],
	["", "ヲﾟ", "ヲ゚", "Katakana Letter Fo"],
	["", "&ジャ;", "ジｬ", "Katakana Letter Zha"],
	["", "&ジュ;", "ジｭ", "Katakana Letter Zhu"],
	["", "&ジェ;", "ジｪ", "Katakana Letter Zhe"],
	["", "&ジョ;", "ジｮ", "Katakana Letter Zho"],
	["", "&ヂャ;", "ヂｬ", "Katakana Letter Ja"],
	["", "&ヂュ;", "ヂｭ", "Katakana Letter Ju"],
	["", "&ヂェ;", "ヂｪ", "Katakana Letter Je"],
	["", "&ヂョ;", "ヂｮ", "Katakana Letter Jo"],
	["", "&ツァ;", "ツｧ", "Katakana Letter Tsa"],
	["", "&ツィ;", "ツｨ", "Katakana Letter Tsi"],
	["", "&ツェ;", "ツｪ", "Katakana Letter Tse"],
	["", "&ツォ;", "ツｫ", "Katakana Letter Tso"],
	["", "&ヅァ;", "ヅｧ", "Katakana Letter Dza"],
	["", "&ヅィ;", "ヅｨ", "Katakana Letter Dzi"],
	["", "&ヅェ;", "ヅｪ", "Katakana Letter Dze"],
	["", "&ヅォ;", "ヅｫ", "Katakana Letter Dzo"],
	["", "&フン;", "フﾝ", "Katakana Letter Hn"],
	["", "&ブン;", "ブﾝ", "Katakana Letter Bn"],
	["", "&チッ;", "チｯ", "Katakana Letter Tsk"],

	["", "&ぃ.;", "&ぃ.;", "Hiragana Letter Small I With Dot Below"],
	["", "&ぅ.;", "&ぅ.;", "Hiragana Letter Small U With Dot Below"],
	["", "&ィ.;", "&ィ.;", "Katakana Letter Small I With Dot Below"],
	["", "&ゥ.;", "&ゥ.;", "Katakana Letter Small U With Dot Below"],

	["", "かﾟ", "か゚", "Hiragana Letter Nga"],
	["", "きﾟ", "き゚", "Hiragana Letter Ngi"],
	["", "くﾟ", "く゚", "Hiragana Letter Ngu"],
	["", "けﾟ", "け゚", "Hiragana Letter Nge"],
	["", "こﾟ", "こ゚", "Hiragana Letter Ngo"],
	["", "カﾟ", "カ゚", "Katakana Letter Nga"],
	["", "キﾟ", "キ゚", "Katakana Letter Ngi"],
	["", "クﾟ", "ク゚", "Katakana Letter Ngu"],
	["", "ケﾟ", "ケ゚", "Katakana Letter Nge"],
	["", "コﾟ", "コ゚", "Katakana Letter Ngo"],
	["", "セﾟ", "セ゚", "Katakana Letter The"],
	["", "ツﾟ", "ツ゚", "Katakana Letter Tsu With Voiced Sound Mark"],
	["", "トﾟ", "ト゚", "Katakana Letter To With Voiced Sound Mark"],
	["", "&ノハプ;", "ㇷ゚", "Katakana Letter Small Pu"],

	["", "さﾟ", "さ゚", "Hiragana Letter Tha"],
	["", "しﾟ", "し゚", "Hiragana Letter Shi With Voiced Sound Mark"],
	["", "すﾟ", "す゚", "Hiragana Letter Thu"],
	["", "せﾟ", "せ゚", "Hiragana Letter The"],
	["", "そﾟ", "そ゚", "Hiragana Letter Tho"],
	["", "サﾟ", "サ゚", "Katakana Letter Tha"],
	["", "シﾟ", "シ゚", "Katakana Letter Shi With Voiced Sound Mark"],
	["", "スﾟ", "ス゚", "Katakana Letter Thu"],
	["", "ソﾟ", "ソ゚", "Katakana Letter Tho"],
	["", "ラﾟ", "ラ゚", "Katakana Letter La"],
	["", "リﾟ", "リ゚", "Katakana Letter Li"],
	["", "ルﾟ", "ル゚", "Katakana Letter Lu"],
	["", "レﾟ", "レ゚", "Katakana Letter Le"],
	["", "ロﾟ", "ロ゚", "Katakana Letter Lo"],
	
	["", "&ヴ;", "ヴｩ", "Katakana Letter Vu"],

	["", "&とぅ;", "とｩ", "Hiragana Letter Tu"],
	["", "&どぅ;", "どｩ", "Hiragana Letter Du"],
	["", "&てぃ;", "てｨ", "Hiragana Letter Ti"],
	["", "&でぃ;", "でｨ", "Hiragana Letter Di"],
	["", "&つぃ;", "つｨ", "Hiragana Letter Tsi"],
	["", "&づぃ;", "づｨ", "Hiragana Letter Dzi"],

	["", "&チャ;", "チｬ", "Katakana Letter Cha"],
	["", "&チュ;", "チｭ", "Katakana Letter Chu"],
	["", "&チェ;", "チｪ", "Katakana Letter Che"],
	["", "&チョ;", "チｮ", "Katakana Letter Cho"],
	["", "&シャ;", "シｬ", "Katakana Letter Sha"],
	["", "&シュ;", "シｭ", "Katakana Letter Shu"],
	["", "&シェ;", "シｪ", "Katakana Letter She"],
	["", "&ショ;", "シｮ", "Katakana Letter Sho"],
	["", "&トゥ;", "トｩ", "Katakana Letter Tu"],

	["", "&_す;", "ｹすｾ", "Hiragana Letter Kesen Si"],
	["", "&_ず;", "ｹずｾ", "Hiragana Letter Kesen Zi"],
	["", "&_ち;", "ｹちｾ", "Hiragana Letter Kesen Ti"],
	["", "&_ぢ;", "ｹぢｾ", "Hiragana Letter Kesen Di"],

	["", "らﾟ", "ら゚", "Hiragana Letter La"],
	["", "れﾟ", "れ゚", "Hiragana Letter Le"],
	["", "ろﾟ", "ろ゚", "Hiragana Letter Lo"],

	["𛀁", "&いぇ;", "いｪ", "Hiragana Letter Ye"],
	["𛀆", "&いぃ;", "いｨ", "Hiragana Letter Yi"],
	["𛄟", "&うぅ;", "うｩ", "Hiragana Letter Wu"],
	["𛄠", "&イィ;", "イｨ", "Katakana Letter Yi"],
	["𛄡", "&イェ;", "イｪ", "Katakana Letter Ye"],
	["𛄢", "&ウゥ;", "ウｩ", "Katakana Letter Wu"],

	["𛄲", "&ノハこ;", "ノﾊこ", "Hiragana Letter Small Ko"],
	["𛅄", "&ノハへ;", "ノﾊへ", "Hiragana Letter Small He"],
	["𛅐", "&ぅぃ;", "ぅｨ", "Hiragana Letter Small Wi"],
	["𛅑", "&ぅぇ;", "ぅｪ", "Hiragana Letter Small We"],
	["𛅒", "&ぅぉ;", "ぅｫ", "Hiragana Letter Small Wo"],
	["𛅓", "&ノハん;", "ノﾊん", "Hiragana Letter Small N"],
	["𛅕", "&ノハコ;", "ノﾊコ", "Katakana Letter Small Ko"],
	["𛅤", "&ゥィ;", "ゥｨ", "Katakana Letter Small Wi"],
	["𛅥", "&ゥェ;", "ゥｪ", "Katakana Letter Small We"],
	["𛅦", "&ゥォ;", "ゥｫ", "Katakana Letter Small Wo"],
	["𛅧", "&ノハン;", "ノﾊン", "Katakana Letter Small N"],

	["󷰸", "&ぃぃ;", "ぃｨ", "Hiragana Letter Small Yi"],
	["󷰹", "&ぃぇ;", "ぃｪ", "Hiragana Letter Small Ye"],
	["󷰺", "&ぅぅ;", "ぅｩ", "Hiragana Letter Small Wu"],
	["󷰻", "&ィィ;", "ィｨ", "Katakana Letter Small Yi"],
	["󷰼", "&ィェ;", "ィｪ", "Katakana Letter Small Ye"],
	["󷰽", "&ゥゥ;", "ゥｩ", "Katakana Letter Small Wu"],

	["ゔ", "うﾞ", "ゔ", "Hiragana Letter Vu"],

	["", "ﾞﾟ", "゙ﾟ", "Combining Katakana-Hiragana Voiced Semi-Voiced Sound Mark"],
	["", "ﾞﾟ", "゛ﾟ", "Katakana-Hiragana Voiced Semi-Voiced Sound Mark"],
	["", "ﾞﾟ", "ﾞﾟ", "Halfwidth Katakana-Hiragana Voiced Semi-Voiced Sound Mark"]
];